// Developer Express Code Central Example:
// How to create custom legend radio buttons to control visibility of a chart series
// 
// This example demonstrates how to show a distribution law (Normal, Uniform or
// Exponential) applied to series points, depending on the selection state of a
// custom radio button in the chart legend.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E4951

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomCheckboxesInLegendViewAndBehavior.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
