' Developer Express Code Central Example:
' How to create custom legend radio buttons to control visibility of a chart series
' 
' This example demonstrates how to show a distribution law (Normal, Uniform or
' Exponential) applied to series points, depending on the selection state of a
' custom radio button in the chart legend.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E4951
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18051
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace CustomCheckboxesInLegendViewAndBehavior.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As CustomCheckboxesInLegendViewAndBehavior.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New CustomCheckboxesInLegendViewAndBehavior.Properties.Settings())), CustomCheckboxesInLegendViewAndBehavior.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return CustomCheckboxesInLegendViewAndBehavior.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
